"""
Train a domain-specific scripture reranker using Sentence Transformers.

Uses the training data generated by generate_reranker_training_data.py.

Based on: https://huggingface.co/blog/train-reranker
"""

import json
from pathlib import Path

import torch
from datasets import Dataset
from sentence_transformers.cross_encoder import (
    CrossEncoder,
    CrossEncoderTrainer,
    CrossEncoderTrainingArguments,
)
from sentence_transformers.cross_encoder.evaluation import (
    CrossEncoderRerankingEvaluator,
)
from sentence_transformers.cross_encoder.losses import BinaryCrossEntropyLoss

TRAINING_DIR = Path(__file__).parent.parent / "reranker_training"
OUTPUT_DIR = Path(__file__).parent.parent / "models" / "scripture-reranker"

# Model options (uncomment one):
# BASE_MODEL = "cross-encoder/ms-marco-MiniLM-L6-v2"  # Fast, good starting point
# BASE_MODEL = "BAAI/bge-reranker-base"  # Designed for RAG
BASE_MODEL = "answerdotai/ModernBERT-base"  # Latest, 8K context


def load_training_data(data_path: Path) -> Dataset:
    """Load training data from Hugging Face dataset or JSON."""
    from datasets import load_from_disk

    # Try loading as HF dataset first
    if data_path.is_dir():
        dataset = load_from_disk(str(data_path))
        # Convert to ST format if needed
        if "text1" not in dataset.column_names:
            dataset = dataset.rename_columns({
                "query": "text1",
                "document": "text2",
            })
        return dataset

    # Fall back to JSON
    with open(data_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    return Dataset.from_dict({
        "text1": data["query"],
        "text2": data["document"],
        "label": data["label"],
    })


def load_full_training_data(data_path: Path) -> tuple[dict, list[dict]]:
    """Load full training data for creating evaluation samples."""
    from datasets import load_from_disk, DatasetDict

    # Load HF dataset or JSON
    if data_path.is_dir():
        dataset_dict = load_from_disk(str(data_path))
        # Combine train and test for evaluation samples
        if isinstance(dataset_dict, DatasetDict):
            data = list(dataset_dict["train"]) + list(dataset_dict["test"])
        else:
            data = list(dataset_dict)
    else:
        with open(data_path, "r", encoding="utf-8") as f:
            data = json.load(f)

    # Group by query for evaluation
    query_docs = {}
    for item in data:
        query = item["query"]
        if query not in query_docs:
            query_docs[query] = {"positives": [], "negatives": []}

        raw_score = item.get("raw_score", int(item.get("label", 0) * 3))
        if raw_score >= 2:
            query_docs[query]["positives"].append(item["document"])
        else:
            query_docs[query]["negatives"].append(item["document"])

    # Create evaluation samples
    eval_samples = []
    for query, docs in query_docs.items():
        if docs["positives"] and docs["negatives"]:
            eval_samples.append({
                "query": query,
                "positive": docs["positives"][:3],  # Up to 3 positives
                "documents": docs["negatives"][:10],  # Up to 10 negatives
            })

    return query_docs, eval_samples


def create_hard_negatives_dataset(data_path: Path) -> Dataset:
    """Create dataset with soft labels from relevance scores."""
    from datasets import load_from_disk, DatasetDict

    # Load HF dataset or JSON
    if data_path.is_dir():
        dataset_dict = load_from_disk(str(data_path))
        if isinstance(dataset_dict, DatasetDict):
            # Combine train split for training
            dataset = dataset_dict["train"]
        else:
            dataset = dataset_dict

        # Convert raw_score to soft labels if present
        if "raw_score" in dataset.column_names:
            score_map = {0: 0.0, 1: 0.2, 2: 0.7, 3: 1.0}
            labels = [score_map.get(s, 0.0) for s in dataset["raw_score"]]
            dataset = dataset.add_column("soft_label", labels)
            dataset = dataset.rename_columns({
                "query": "text1",
                "document": "text2",
                "soft_label": "label",
            })
            dataset = dataset.select_columns(["text1", "text2", "label"])
        return dataset

    # Fall back to JSON
    with open(data_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    queries = []
    documents = []
    labels = []

    for item in data:
        queries.append(item["query"])
        documents.append(item.get("document_text", item.get("document", "")))
        score = item.get("relevance_score", item.get("raw_score", 0))
        score_map = {0: 0.0, 1: 0.2, 2: 0.7, 3: 1.0}
        labels.append(score_map.get(score, 0.0))

    return Dataset.from_dict({
        "text1": queries,
        "text2": documents,
        "label": labels,
    })


def find_latest_training_file(pattern: str = "scripture_reranker_dataset_*") -> Path | None:
    """Find the most recent training data (HF dataset directory or JSON file)."""
    # First try HF dataset directories
    dirs = [d for d in TRAINING_DIR.glob(pattern) if d.is_dir()]
    if dirs:
        return max(dirs, key=lambda p: p.stat().st_mtime)

    # Fall back to JSON files
    files = list(TRAINING_DIR.glob("training_data_full_*.json"))
    if files:
        return max(files, key=lambda p: p.stat().st_mtime)

    return None


def main():
    """Train the scripture reranker."""
    import argparse

    parser = argparse.ArgumentParser(description="Train scripture reranker")
    parser.add_argument("--data", type=str, default=None,
                        help="Path to training data (default: latest)")
    parser.add_argument("--model", type=str, default=BASE_MODEL,
                        help=f"Base model (default: {BASE_MODEL})")
    parser.add_argument("--epochs", type=int, default=3,
                        help="Training epochs (default: 3)")
    parser.add_argument("--batch-size", type=int, default=16,
                        help="Batch size (default: 16)")
    parser.add_argument("--lr", type=float, default=2e-5,
                        help="Learning rate (default: 2e-5)")
    args = parser.parse_args()

    print("Scripture Reranker Training")
    print("=" * 60)

    # Find training data
    if args.data:
        data_path = Path(args.data)
    else:
        data_path = find_latest_training_file()

    if not data_path or not data_path.exists():
        print("Error: No training data found.")
        print("Run generate_reranker_training_data.py first.")
        return

    print(f"Training data: {data_path}")
    print(f"Base model: {args.model}")
    print(f"Epochs: {args.epochs}")
    print(f"Batch size: {args.batch_size}")
    print(f"Learning rate: {args.lr}")
    print()

    # Load data
    print("Loading training data...")
    train_dataset = create_hard_negatives_dataset(data_path)
    print(f"  Loaded {len(train_dataset):,} examples")

    # Split into train/eval
    split = train_dataset.train_test_split(test_size=0.1, seed=42)
    train_data = split["train"]
    eval_data = split["test"]
    print(f"  Train: {len(train_data):,}, Eval: {len(eval_data):,}")

    # Load full data for reranking evaluator
    _, eval_samples = load_full_training_data(data_path)
    print(f"  Evaluation samples: {len(eval_samples)}")

    # Initialize model
    print(f"\nLoading base model: {args.model}")
    model = CrossEncoder(args.model, num_labels=1)

    # Define loss
    # pos_weight helps with imbalanced data (usually more negatives than positives)
    pos_count = sum(1 for ex in train_data if ex["label"] > 0.5)
    neg_count = len(train_data) - pos_count
    pos_weight = neg_count / max(pos_count, 1)
    print(f"Positive/Negative ratio: {pos_count}/{neg_count} (weight: {pos_weight:.2f})")

    loss = BinaryCrossEntropyLoss(
        model=model,
        pos_weight=torch.tensor(min(pos_weight, 5.0)),  # Cap at 5
    )

    # Define evaluator
    evaluator = None
    if eval_samples:
        evaluator = CrossEncoderRerankingEvaluator(
            samples=eval_samples[:100],  # Use up to 100 samples
            batch_size=args.batch_size,
            name="scripture-rerank-eval",
        )

    # Training arguments
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    training_args = CrossEncoderTrainingArguments(
        output_dir=str(OUTPUT_DIR),
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        learning_rate=args.lr,
        warmup_ratio=0.1,
        fp16=torch.cuda.is_available(),
        bf16=False,
        eval_strategy="steps" if evaluator else "no",
        eval_steps=500,
        save_strategy="steps",
        save_steps=500,
        save_total_limit=3,
        load_best_model_at_end=True if evaluator else False,
        metric_for_best_model="eval_ndcg@10" if evaluator else None,
        logging_steps=100,
        report_to="none",  # Disable wandb/tensorboard
    )

    # Create trainer
    trainer = CrossEncoderTrainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=eval_data if evaluator else None,
        loss=loss,
        evaluator=evaluator,
    )

    # Train
    print("\nStarting training...")
    print("=" * 60)
    trainer.train()

    # Save final model
    final_path = OUTPUT_DIR / "final"
    model.save_pretrained(str(final_path))
    print(f"\nModel saved to: {final_path}")

    # Test the model
    print("\n" + "=" * 60)
    print("TESTING TRAINED MODEL")
    print("=" * 60)

    test_queries = [
        ("Who was Nephi?", "I, Nephi, having been born of goodly parents, therefore I was taught somewhat in all the learning of my father."),
        ("Who was Nephi?", "And it came to pass that the people of Nephi did till the land."),
        ("What is faith?", "And now as I said concerning faith—faith is not to have a perfect knowledge of things."),
        ("What is faith?", "And it came to pass that they did go forth."),
    ]

    print("\nSample predictions:")
    for query, doc in test_queries:
        score = model.predict([(query, doc)])[0]
        print(f"\nQuery: {query}")
        print(f"Doc: {doc[:60]}...")
        print(f"Score: {score:.4f}")


if __name__ == "__main__":
    main()
